### ISSUE TITLE
Ledger From Tanaris - Missing quest item

### ISSUE THREAD

**Issue by impcezar** [elysium-project/classic-bug-tracker#913] opened 2018-10-14 06:53 UTC
quest "Ledger From tanaris"  
https://classicdb.ch/?quest=4450
"Goodsteel Ledger"  this item  missing
https://classicdb.ch/?object=173266

**Comment by Vasquez-QA** [comment] 2018-10-14 11:42
Tested and confirmed.

**Intended Behaviour:**

Quest "Ledger from Tanaris" from Searing Gorge (GUID 4450) should give you item "Goodsteel Ledger" (GUID 173266) which details the required materials needed to complete request.

**Current Bugged Behavior:**

When the quest is accepted, no such item is given.

Sources:

Information on the quest and item can be found here: 
- https://classicdb.ch/?quest=8736
- https://classicdb.ch/?object=173266

Video:

- https://www.youtube.com/watch?v=J2N1wKmRkVE (1 hour. 47 minutes in)

**Comment by impcezar** [comment] 2018-10-14 20:59
so, there it item?
https://youtu.be/YtM3pydeOHQ

**Comment by Vasquez-QA** [comment] 2018-10-25 21:38
Now fixed on PTR - ready to be patched to live.

**Closed** 2018-12-30 10:33 UTC
Labels: Confirmed, Fixed and tested ready for live!
