### ISSUE TITLE
Sold Items on AH but didn't get Gold

### ISSUE THREAD

**Issue by Sovern-priest** [elysium-project/classic-bug-tracker#918] opened 2018-10-16 00:35 UTC
Elysium Dev Team,

I recently sold some items on the Auction House. When i opened the mailbox, the mail letters confirmed i sold the items for the specified the amount, but there was no attachment with gold.

I have left the mail in my mailbox to help with the investigation. I also took a screenshot and can provide it, if needed.

Total Amount: 3g 90s 95c

**Comment by ZicoQA** [comment] 2019-01-03 01:04
Since no one else has reported this bug I will close it as I can't replicate and ah and mail looks like working as intended

**Closed by ZicoQA** 2019-01-03 01:04 UTC
Labels: Waiting for Player Response
