### ISSUE TITLE
Unable to search auction house for random suffixes ("of the Monkey")

### ISSUE THREAD

**Issue by Inomares** [elysium-project/classic-bug-tracker#406] opened 2018-02-08 04:22 UTC
Repro:
1) If needed for your test realm, create an item which spawns with a random suffix, such as 15304 (Grizzly Jerkin of the <random suffix>) and put it on the auction house
2) Attempt to search the auction house for a random suffix such as "of the Monkey" or "of Frozen Wrath". If you created a new item in step 1, just use the suffix you got.
3) Note that no items appear in the search result.

This was originally fixed on retail with [Patch 1.8](http://wowwiki.wikia.com/wiki/Patch_1.8.0):
>You can now search for random suffixes such as "of the Monkey" in the Auction House.

**Comment by Terranzin** [comment] 2018-02-08 07:20
We´re on patch 1.5

**Comment by Inomares** [comment] 2018-02-08 14:04
@Terranzin This isn't exactly a matter of content progression though.

**Comment by Terranzin** [comment] 2018-02-08 18:23
We´re not going to add smaller functionalities like this, it will be released together with patch 1.8.

**Comment by Inomares** [comment] 2018-07-19 15:47
@Thenari This can now be reopened as we are now on patch 1.8

**Comment by Thenari** [comment] 2018-07-19 16:09
Oh nice ah search upgrade will be handy. Is this not working now? Ill reopen it but idk much else

**Comment by Inomares** [comment] 2018-07-19 20:50
Correct, this is not working now.

**Comment by Thenari** [comment] 2018-08-09 22:31
So we should be in 1.9 now right? Gonna go ahead and slap a high priority on it.

**Comment by Thenari** [comment] 2018-08-25 00:55
Im afraid to put the good first issue cause i want an experienced Dev to do this as a AH mess up would be really bad. But i will say you can always put your code updates to ptr and get a go ahead from a higher up dev to check :)

**Comment by ZicoQA** [comment] 2018-12-25 10:14
This is now working as intended

**Closed** 2018-12-25 10:14 UTC
Labels: Fixed on Live
