### ISSUE TITLE
Digging through the Ooze not dropping Sida's bag

### ISSUE THREAD

**Issue by Zachkey** [elysium-project/classic-bug-tracker#1082] opened 2019-02-12 22:40 UTC
Quest ID and link : http://classicdb.ch/?quest=470

Item ID and link : http://classicdb.ch/?item=3352

Spent an hour farming, reset UI, relogged, tried resetting the quest; and nothing seemed to work.

**Comment by cmdrkeen84** [comment] 2019-02-18 18:07
This item was always considered a very hard to obtain rare drop. The easiest way to obtain this item was to group up with multiple people and put the loot on Free for all. This makes the game do a quest item loot check not just for the individual whos looting but for every single person in your group up to 5 people. And with all quest objective items when 1 person finds it under FFA all people find it.

**Comment by saltyqa** [comment] 2019-03-06 21:36
@Zachkey as @cmdrkeen84 said, this has always been known to be a very low drop rate quest. Closing issue as not a bug.

**Closed by saltyqa** 2019-03-06 21:36 UTC
