### ISSUE TITLE
Epic turtle mount bug

### ISSUE THREAD

**Issue by duvawarr** [elysium-project/classic-bug-tracker#894] opened 2018-09-27 15:47 UTC
When you ride on epic turtle mount from shop 250 coins, it says slow and steady. therefor it cant be used for lazypig/Ezdismount addon cant dismount it.

it is epic please fix, it says 100% speed.

**Comment by pl4ything** [comment] 2018-09-27 15:56
Some addons search for mounts by looking at tooltips for "increases speed by %". think the tooltip for the Swift Riding Turtle was copied over from the Slow Riding Turtle and it should be edited to show the speed bonus.

**Comment by Thenari** [comment] 2018-09-27 16:46
this is a duplicate of #805 closing as duplicate

**Closed by Thenari** 2018-09-27 16:46 UTC
Labels: Good First Issue, Low Priority

**Comment by Thenari** [comment] 2018-09-27 16:47
basically its an addon, addon works by manually dispelling ever mount in the game at the same time, if you know the addon creator or are comfortable yourself
you can go into the file and put in the /use item turtle mount to the master dismount list

**Comment by Thenari** [comment] 2018-09-27 16:48
it is not our addon it isnt in the vanilla game to auto dismount we would have to force the download onto everyone playing on our server, its way easier and more consensual for you to modifiy your own addon

**Comment by Thenari** [comment] 2018-09-27 16:51
i think satan666 https://github.com/satan666/_LP "made" lazypig? there may be a bunch of versions i don't know these thing there might be a read me you can use to modify your own files

**Comment by Thenari** [comment] 2018-09-27 16:52
theres 3 issue reports #805 was the first #838 rain commnted in so thats the on we using

**Comment by pl4ything** [comment] 2018-09-27 17:00
@Thenari 
The addon (Lazypig, unsure about Ezdismount) doesn't use a list of mounts to disable it searches the tooltips of your current buffs for a movement speed increase and since the swift riding turtle tooltip is "slow and steady" instead of "increases movement speed by X". I understand this is a problem with a select few addons hence the "low priority" tag but i feel like it is also a standards issue that needs to be addressed with the developers to ensure that items created for the server are up to blizzard level of 'this is ok to push to a live ream' so we don't continue to get silly things like this that are easily fixed.

**Comment by pl4ything** [comment] 2018-09-27 17:29
the first thing I did was add low priority and good first issue....it isn't a game breaking bug but it is a thing that can easily be fixed by whomever creates new mounts create new _accurate_ tooltips for each mount instead of copying them over from wherever they got them from.

**Comment by Thenari** [comment] 2018-09-27 17:32
Just changing the name of the spell id tooltip will fix it?

**Comment by Thenari** [comment] 2018-09-27 17:42
All the deletes are my rambling. Ignore that.
